### PR TITLE
update conan

### PR DESCRIPTION
**Pull request by reiinakano**
It seems we need to update here too.

### CODE REVIEW

**Review by kenichi-fukushima — APPROVED** [review]

**Comment by anuraaga** [comment]
We should actually release a new `stellarstation-api` version and reference it here, rather than adding a transitive gRPC version like this. Does `gr-stellarstation` still work even with monitoring messages? I know `stellarcli` had some issues, and suspect we need to update anyways. What do you think?

**Comment by reiinakano** [comment]
I haven't tested this in a while so yeah it'll probably break.

**Comment by reiinakano** [comment]
I'll wait for the release then and come back to this later

**Comment by reiinakano** [comment]
@rtubio How urgently do you need a functional gr-stellarstation?

**Comment by rtubio** [comment]
@reiinakano actually it is not very urgent either for me or four our customers, so I can try to work something around this issue. Some customers (like Vigo) were very interested on integrating directly with a GNU Radio block, although they have not expressed their interested again on this feature for the last months.

Please keep me in the loop for whenever the gr blocks are working again.

**Pull request closed without merging**
